"""Snapshot-based lexical VB code navigation. Never a compiler-resolved dependency graph."""
from __future__ import annotations
import json
import re
from pathlib import Path
from bisect import bisect_right
from .common import database, digest, dump, now, search_expression, ResearchError

EXCLUDE_DIRS={'bin','obj','backup','backups','packages','.git','node_modules','ref','reference'}
EXCLUDE_NAMES=('designer.','assemblyinfo.','globalusings.','.generated.','.g.vb','.g.cs')
VB_START=re.compile(r'^\s*(?:(?:Public|Private|Protected|Friend|Shared|Partial|Overrides|Overloads|Overridable|NotOverridable|MustOverride|Iterator|Async|Default|ReadOnly|WriteOnly|Static)\s+)*(Sub|Function|Property)\s+(\w+)\b',re.I)
VB_END=re.compile(r'^\s*End\s+(Sub|Function|Property)\b',re.I)


def clean_vb(line):
    out=[];i=0;quoted=False
    while i<len(line):
        ch=line[i]
        if ch=='"':
            if quoted and i+1<len(line) and line[i+1]=='"':i+=2;continue
            quoted=not quoted;out.append(' ')
        elif not quoted:
            if ch=="'":break
            out.append(ch)
        i+=1
    text=''.join(out)
    return '' if re.match(r'^\s*Rem\b',text,re.I) else text


def routines(lines):
    result=[];current=None
    for number,line in enumerate(lines,1):
        code=clean_vb(line)
        start=VB_START.match(code)
        if start:
            if current:
                current['end']=number-1;current['boundary_warning']='Unclosed lexical routine boundary';result.append(current)
            current={'name':start.group(2),'kind':start.group(1),'start':number,'end':len(lines),'boundary_warning':None}
        end=VB_END.match(code)
        if current and end and end.group(1).lower()==current['kind'].lower():
            current['end']=number;result.append(current);current=None
    if current:
        current['boundary_warning']='No lexical end marker found';result.append(current)
    return result


def phase(path):
    return 'rebuild/initialization' if '.rebuild.' in path.lower() else 'forecast (may include first-year initialization)' if '.forecast.' in path.lower() else 'shared/unspecified'


def assignment_lhs(code, symbol):
    # Only statements beginning with the symbol, not If X = Y comparisons.
    m=re.match(r'^\s*(?:Let\s+|Set\s+)?'+re.escape(symbol)+r'(?!\w)[%!#$&@]?',code,re.I)
    if not m:return False
    rest=code[m.end():].lstrip()
    if rest.startswith('('):
        depth=0;end=None
        for i,c in enumerate(rest):
            if c=='(':depth+=1
            elif c==')':
                depth-=1
                if depth==0:end=i+1;break
        if end is None:return False
        rest=rest[end:].lstrip()
    return bool(re.match(r'(?:[+\-*/\\^&]=|=(?!=))',rest))


class CodeStore:
    def __init__(self,path):
        self.path=path
        with database(path) as db:
            db.executescript('''
            CREATE TABLE IF NOT EXISTS code_snapshots(id TEXT PRIMARY KEY,root TEXT,created_at TEXT,manifest TEXT);
            CREATE TABLE IF NOT EXISTS code_current(singleton INTEGER PRIMARY KEY CHECK(singleton=1),snapshot TEXT);
            CREATE TABLE IF NOT EXISTS code_files(snapshot TEXT,path TEXT,sha256 TEXT,encoding TEXT,body TEXT,PRIMARY KEY(snapshot,path));
            CREATE TABLE IF NOT EXISTS code_routines(id TEXT PRIMARY KEY,snapshot TEXT,path TEXT,name TEXT,kind TEXT,start INTEGER,end INTEGER,warning TEXT);
            CREATE VIRTUAL TABLE IF NOT EXISTS code_fts USING fts5(snapshot UNINDEXED,path UNINDEXED,line UNINDEXED,routine UNINDEXED,clean,raw);
            ''')

    def index(self,root):
        root=Path(root).resolve()
        if not root.is_dir():raise ResearchError('Code root does not exist')
        if root==Path(self.path).resolve().parent or root in Path(self.path).resolve().parents:
            raise ResearchError('Code index must not be written into source tree')
        files=[];skipped=[]
        for path in sorted(root.rglob('*')):
            if not path.is_file():continue
            relative=path.relative_to(root)
            if path.is_symlink() or not path.resolve().is_relative_to(root):
                skipped.append(str(relative));continue
            if path.suffix.lower() not in ('.vb','.cs'):continue
            if any(part.lower() in EXCLUDE_DIRS for part in relative.parts[:-1]) or any(n in path.name.lower() for n in EXCLUDE_NAMES):
                skipped.append(str(relative));continue
            raw=path.read_bytes()
            if len(raw)>16*1024*1024:raise ResearchError(f'Source file too large: {relative}')
            try:body=raw.decode('utf-8-sig');encoding='utf-8-sig'
            except UnicodeDecodeError:body=raw.decode('cp1252');encoding='cp1252'
            # Header-marked generated files are not authoritative mechanism sources.
            if '<auto-generated' in body[:2000].lower():skipped.append(str(relative));continue
            files.append((relative.as_posix(),digest(raw),encoding,body))
        if not files:raise ResearchError('No active VB/C# source files found')
        manifest={'files':[{'path':p,'sha256':h,'encoding':e} for p,h,e,b in files],
                  'excluded':skipped,'parser':'lexical-v1','limitations':['No compiler binding, scope resolution, or conditional-compilation evaluation.',
                  'VB routine boundaries are heuristic; C# supports lexical search only.']}
        sid=digest(dump({'root':str(root),'files':manifest['files'],'parser':manifest['parser']}))
        # Catch changes during inventory before making a complete snapshot active.
        if any(digest((root/p).read_bytes())!=h for p,h,e,b in files):raise ResearchError('Code changed during indexing; retry')
        with database(self.path) as db:
            if not db.execute('SELECT 1 FROM code_snapshots WHERE id=?',(sid,)).fetchone():
                db.execute('INSERT INTO code_snapshots VALUES(?,?,?,?)',(sid,str(root),now(),dump(manifest)))
                for path,sha,enc,body in files:
                    db.execute('INSERT INTO code_files VALUES(?,?,?,?,?)',(sid,path,sha,enc,body))
                    lines=body.splitlines();rs=routines(lines) if path.lower().endswith('.vb') else []
                    for r in rs:
                        rid=f'{sid}:{path}:{r["start"]}'
                        db.execute('INSERT INTO code_routines VALUES(?,?,?,?,?,?,?,?)',
                                   (rid,sid,path,r['name'],r['kind'],r['start'],r['end'],r['boundary_warning']))
                    starts=[r['start'] for r in rs];records=[]
                    for number,line in enumerate(lines,1):
                        if not line.strip():continue
                        i=bisect_right(starts,number)-1
                        routine=f'{sid}:{path}:{rs[i]["start"]}' if i>=0 and number<=rs[i]['end'] else None
                        clean=clean_vb(line) if path.lower().endswith('.vb') else re.sub(r'"(?:\\.|[^"\\])*"|//.*',' ',line)
                        records.append((sid,path,number,routine,clean,line))
                    db.executemany('INSERT INTO code_fts VALUES(?,?,?,?,?,?)',records)
            db.execute('INSERT OR REPLACE INTO code_current VALUES(1,?)',(sid,))
        return {'snapshot':sid,'files':len(files),'excluded':skipped,'limitations':manifest['limitations']}

    def current(self):
        with database(self.path) as db:row=db.execute('SELECT snapshot FROM code_current WHERE singleton=1').fetchone()
        if not row:raise ResearchError('Index the code source first')
        return row[0]

    def status(self,snapshot=None):
        with database(self.path) as db:
            row=db.execute('SELECT * FROM code_snapshots WHERE id=?',(snapshot,)).fetchone() if snapshot else db.execute('SELECT s.* FROM code_snapshots s JOIN code_current c ON c.snapshot=s.id').fetchone()
        if not row:return {'indexed':False}
        return {'indexed':True,'snapshot':row['id'],'root':row['root'],'created_at':row['created_at'],**json.loads(row['manifest'])}

    def search(self,query,limit=20,offset=0,snapshot=None,references=False,literal=False):
        if offset<0:raise ResearchError('Negative search offset')
        sid=snapshot or self.current();limit=max(1,min(int(limit),100))
        if not query or (literal and references):raise ResearchError('Provide a nonempty query and choose literal or references')
        expression=query if literal else search_expression(query)
        if references:
            if not re.fullmatch(r'[A-Za-z_]\w*',query):raise ResearchError('References require one identifier')
            expression='clean : ('+expression+')'
        with database(self.path) as db:
            # FTS tokenization splits underscores: verify actual identifier boundaries too.
            identifier=re.compile(r'(?<!\w)'+re.escape(query)+r'(?!\w)',re.I)
            db.create_function('symbol_match',1,lambda line:int(bool(identifier.search(line))))
            where=('instr(raw,?)>0' if literal else 'code_fts MATCH ?')+' AND snapshot=?'+(' AND symbol_match(clean)=1' if references else '')
            total=db.execute('SELECT count(*) FROM code_fts WHERE '+where,(expression,sid)).fetchone()[0]
            rows=db.execute('SELECT path,line,routine,clean,raw FROM code_fts WHERE '+where+
                            ' ORDER BY path,CAST(line AS INTEGER) LIMIT ? OFFSET ?',(expression,sid,limit,offset)).fetchall()
        hits=[]
        for row in rows:
            kind='lexical_occurrence'
            if references:
                if assignment_lhs(row['clean'],query):kind='assignment_candidate'
                elif re.match(r'^\s*(?:Public|Private|Friend|Protected|Dim|Const|Static)\b',row['clean'],re.I) and re.search(r'\b'+re.escape(query)+r'\b',row['clean'],re.I):kind='declaration_or_signature_candidate'
            hits.append({'path':row['path'],'line':row['line'],'text':row['raw'],'kind':kind,'routine_id':row['routine'],
                         'phase':phase(row['path']),'citation':{'snapshot':sid,'path':row['path'],'line':row['line']}})
        return {'snapshot':sid,'total':total,'hits':hits,'next_offset':offset+limit if offset+limit<total else None,
                'limitations':'Lexical matches, not compiler-resolved dependencies or proof of causality.'}

    def read(self,path,start=1,end=None,snapshot=None):
        sid=snapshot or self.current()
        with database(self.path) as db:
            row=db.execute('SELECT f.*,s.root FROM code_files f JOIN code_snapshots s ON s.id=f.snapshot WHERE f.snapshot=? AND f.path=?',(sid,path)).fetchone()
        if not row:raise ResearchError('File not present in selected source snapshot')
        lines=row['body'].splitlines();end=min(len(lines),start+199) if end is None else end
        if start<1 or end<start or start>len(lines) or end-start>=500:raise ResearchError('Read requires valid lines, at most 500 per request')
        end=min(end,len(lines));source=Path(row['root'])/path
        unchanged=source.is_file() and digest(source.read_bytes())==row['sha256']
        return {'snapshot':sid,'path':path,'sha256':row['sha256'],'encoding':row['encoding'],
                'start':start,'end':end,'total_lines':len(lines),'next_line':end+1 if end<len(lines) else None,
                'text':'\n'.join(f'{i}: {lines[i-1]}' for i in range(start,end+1)),
                'local_source':str(source),'local_source_matches_snapshot':unchanged,'phase':phase(path),
                'citation':{'snapshot':sid,'path':path,'start':start,'end':end}}

    def find_routines(self,name,limit=50):
        with database(self.path) as db:
            return [dict(r) for r in db.execute('SELECT * FROM code_routines WHERE snapshot=? AND lower(name)=lower(?) ORDER BY path,start LIMIT ?',
                                                (self.current(),name,max(1,min(limit,100))))]

    def read_routine(self,routine_id,offset=0):
        with database(self.path) as db:r=db.execute('SELECT * FROM code_routines WHERE id=?',(routine_id,)).fetchone()
        if r is None:raise ResearchError('Unknown routine ID')
        if offset<0 or r['start']+offset>r['end']:raise ResearchError('Invalid routine offset')
        start=r['start']+offset;end=min(r['end'],start+199)
        result=self.read(r['path'],start,end,r['snapshot'])
        return {**result,'routine':dict(r),'next_offset':offset+200 if end<r['end'] else None,
                'boundary_notice':'Lexically detected VB routine; verify displayed source context.'}
